GET http://localhost:3000/classes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInByZWZlcnJlZF91c2VybmFtZSI6ImZyb2xhbmQiLCJpYXQiOjE2MzkzOTkwMzUsImV4cCI6MTYzOTQ4NTQzNSwiYXVkIjoiTW9uUHJvamV0RGVtbyBBUEkiLCJpc3MiOiJNb25Qcm9qZXREZW1vIHRva2VuIGdlbmVyYXRvciJ9.Ie3RA3uCP64k71-1rTHVvkzwbeZ5pQ6FNYYCU4S9Fl4
